//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FV_API_Harness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccBusinessUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ccBusinessUnit()
        {
            this.ccProject = new HashSet<ccProject>();
        }
    
        public int buID { get; set; }
        public string buName { get; set; }
        public string buEmail { get; set; }
        public string buPhone { get; set; }
        public int buActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ccProject> ccProject { get; set; }
    }
}
