//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FV_API_Harness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccProject
    {
        public int projectID { get; set; }
        public string projectName { get; set; }
        public string contractCode { get; set; }
        public string wbsCode { get; set; }
        public Nullable<int> buID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> sectorID { get; set; }
        public Nullable<int> contractTypeID { get; set; }
        public string projectleader { get; set; }
        public Nullable<System.DateTime> lastUploaded { get; set; }
        public Nullable<int> ccManager { get; set; }
        public Nullable<int> priority { get; set; }
        public int IsActive { get; set; }
    
        public virtual ccBusinessUnit ccBusinessUnit { get; set; }
    }
}
